### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by SlayerT** [skvsbk/zabbix_template#1]
Через snmp все показывает, а через через скрипт python ошибка

Cartridges (non-original NO) | 29.06.2021 15:41:10 | Arguments error

**Comment by skvsbk** [comment]
Вероятно Вы неправильно вызвали скрипт - не указали действие discovery или element. 
Надо:
 get_ink_level.py  <IP_address>  <discovery|element>

**Comment by SlayerT** [comment]
Да , точно, если запускаю скрипт то все ок , показивает чернила и отработку , но в zabbix 5.4.0  элемент даных Cartridges (non-original NO): Level (Waste) показывает ошибку

Preprocessing failed for: Arguments error
1. Failed: cannot extract value from json by path "$.Waste": cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'Arguments error'

**Comment by skvsbk** [comment]
В discovery rules напишите так:
get_ink_level_epson.py[{HOST.CONN}, "discovery"]

В  items напишите так:
get_ink_level_epson.py[{HOST.CONN}, "element"]

Шаблон zabbix исправил, можете скачать и использовать. Добавил шаблон на русском языке.
В скрипте исправил правильность отображения уровня чернил.

**Comment by SlayerT** [comment]
Спасибо! Все заработало
